image:
  repository: docker.io/rdvansloten/cert-manager-key-vault-sync
  tag: v0.1.1
  pullPolicy: IfNotPresent

replicaCount: 1

# Interval in seconds to check for new certificates
checkInterval: 600

# Is set to true, the namespace name is appended to the certificate name in the Key Vault
# Be aware that having duplicate certificate names in different namespaces will cause constant sync issues
useNamespaces: "false"

azure:
  # Name of the Key Vault, do not enter the full URI here
  keyVaultName: ""

  # Properties of the Managed Identity used to access the Key Vault
  # Ensure that the Managed Identity has at least Key Vault Certificates Officer permissions
  workloadIdentity:
    clientId: ""
    subscriptionId: ""
    tenantId: ""

# Image Pull Secrets, applied to the Service Account 
# Remember, this has to be in the same namespace as the Service Account
imagePullSecrets: []

loggingLevels:
  # Controls the logging level for the Python application
  default: "INFO"
  # Controls the logging level for the Azure SDK components
  azure: "WARNING"

# These resources should be plenty, only raise if you have a huge amount
# of certificates and get OOMKilled errors
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
