apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name | default "cert-manager-key-vault-sync" }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name | default "cert-manager-key-vault-sync" }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name | default "cert-manager-key-vault-sync" }}
  apiGroup: rbac.authorization.k8s.io
