apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.workloadIdentity.tenantId }}
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: cert-manager-key-vault-sync
    app.kubernetes.io/instance: cert-manager-key-vault-sync
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
