apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-key-vault-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-manager-key-vault-sync
    app.kubernetes.io/instance: cert-manager-key-vault-sync
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-key-vault-sync
      app.kubernetes.io/instance: cert-manager-key-vault-sync
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app.kubernetes.io/name: cert-manager-key-vault-sync
        app.kubernetes.io/instance: cert-manager-key-vault-sync
    spec:
      serviceAccountName: cert-manager-key-vault-sync
      containers:
        - name: cert-manager-key-vault-sync
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZURE_KEY_VAULT_NAME
              value: {{ .Values.azure.keyVaultName }}
            - name: CHECK_INTERVAL
              value: "{{ .Values.checkInterval | default 300 }}"
            - name: USE_NAMESPACES
              value: "{{ .Values.useNamespaces | default "false" }}"
            - name: DEFAULT_LOGGING_LEVEL
              value: "{{ .Values.loggingLevels.default | default "INFO" | upper }}"
            - name: AZURE_LOGGING_LEVEL
              value: "{{ .Values.loggingLevels.azure | default "WARNING" | upper }}"
            - name: GITHUB_REPO_OWNER
              value: "{{ .Values.versionCheck.github_repository_owner | default "rdvansloten" }}"
            - name: GITHUB_REPO_NAME
              value: "{{ .Values.versionCheck.github_repository_name | default "cert-manager-key-vault-sync" }}"
            - name: VERSION_CHECK_INTERVAL
              value: "{{ .Values.versionCheck.interval | default 86400 }}"
            - name: CHECK_VERSION
              value: "{{ .Values.versionCheck.enabled | default "true" | lower }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
