apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.workloadIdentity.tenantId }}
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: cert-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
