name: Build and Push Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'app/**'
      - 'Dockerfile'

env:
  IMAGE_NAME: cert-manager-key-vault-sync
  CHART_NAME: cert-manager-key-vault-sync-chart
  REPOSITORY_NAME: rdvansloten
  HELM_REGISTRY_SERVER: registry-1.docker.io

jobs:
  build:
    name: Build and Push Helm Chart
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log into Helm Registry
      run: | 
        echo "${{ secrets.DOCKER_PAT }}" | helm registry login -u ${{ secrets.DOCKER_USERNAME }} ${{ env.HELM_REGISTRY_SERVER }} --password-stdin
    
    - name: Build and push Helm chart
      working-directory: ./charts
      run: |
        CHART_VERSION=$(cat ./${{ env.CHART_NAME }}/Chart.yaml | grep version | awk '{print $2}')
        helm package ${{ env.CHART_NAME }}
        helm push $CHART_NAME-$CHART_VERSION.tgz oci://${{ env.HELM_REGISTRY_SERVER }}/${{ secrets.DOCKER_USERNAME }}