name: Test Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'app/**'
      - 'Dockerfile'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install yq
      run: |
        sudo apt update
        sudo apt install snap -y
        sudo snap install yq

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: false
        tags: ${{ github.repository }}:gh-run-${{ github.run_id }}