name: Test Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'app/**'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: false
        tags: ${{ github.repository }}:gh-run-${{ github.run_id }}
    
    - name: Remove test Docker image from remote
      run: |
        username=${{ secrets.DOCKER_USERNAME }}
        password=${{ secrets.DOCKER_PAT }}
        github_run_id=${{ github.run_id }}
        account_name=${{ secrets.DOCKER_USERNAME }}
        repository_name="cert-manager-key-vault-sync"

        # Authenticate and delete remote image
        token=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": $username, "password": $password}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        image_digest=$(curl -s -H "Authorization: Bearer $token" "https://hub.docker.com/v2/repositories/$account_name/$repository_name/tags/$github_run_id/" | jq -r .images[0].digest)
        curl -s -X DELETE -H "Authorization: Bearer $token" "https://hub.docker.com/v2/repositories/$account_name/$repository_name/manifests/$image_digest/"